package com.wadpam.mardao.oauth.dao;

/**
 * Business Methods interface for entity DConnection.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-01-24T19:43:52.136+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DConnectionDao extends GeneratedDConnectionDao {
    
    static final String PROVIDER_ID_FACEBOOK = "facebook";

    String getAccessToken(Object userKey, String providerId);
	
}
