package com.wadpam.mardao.oauth.dao;

/**
 * Implementation of Business Methods related to entity DFactory.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-01-24T19:43:52.136+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DFactoryDaoBean 
	extends GeneratedDFactoryDaoImpl
		implements DFactoryDao 
{

	// TODO: implement your Business Methods here

}
