package com.wadpam.gugama.oauth.dao;

import com.wadpam.gugama.oauth.domain.DConnection;
import net.sf.mardao.core.Filter;

/**
 * Implementation of Business Methods related to entity DConnection.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-01-24T19:43:52.136+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DConnectionDaoBean 
	extends GeneratedDConnectionDaoImpl
		implements DConnectionDao 
{

    @Override
    public String getAccessToken(Object userKey, String providerId) {
        Filter providerIdFilter = createEqualsFilter(COLUMN_NAME_PROVIDERID, providerId);
        Iterable<DConnection> connections = queryIterable(false, 0, -1, userKey, null, COLUMN_NAME_EXPIRETIME, false, 
                                      null, false, providerIdFilter);
        for (DConnection recent : connections) {
            // TODO: refresh
            return recent.getAccessToken();
        }
        return null;
    }

}
