package com.wadpam.gugama.oauth.dao;

import com.wadpam.gugama.oauth.domain.DOAuth2User;

/**
 * Business Methods interface for entity DOAuth2User.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-01-24T19:43:52.136+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DOAuth2UserDao extends GeneratedDOAuth2UserDao {

}
